
"use client"; // Required for useEffect to run client-side for theme application

import React, { useEffect } from 'react'; // Import React and useEffect
// import type {Metadata} from 'next'; // Metadata is commented out, can be removed if not planned
import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { BottomNavBar } from '@/components/layout/BottomNavBar';

// Metadata cannot be dynamically changed by client components,
// so we define it statically here.
// For dynamic titles/descriptions per page, use the generateMetadata function in page.tsx files.
// export const metadata: Metadata = {
// title: 'PR Visualizer',
// description: 'Generated by Firebase Studio, customized for PR Visualizer',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    // Apply theme on initial client-side load
    const applyInitialTheme = () => {
      const storedTheme = localStorage.getItem('appTheme');
      const root = window.document.documentElement;
      root.classList.remove('light', 'dark'); // Clear existing theme classes

      if (storedTheme === 'dark' || (!storedTheme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
        root.classList.add('dark');
      } else {
        // Defaults to light if no theme stored and system is not dark, or if 'light' is stored
        root.classList.add('light');
      }
    };

    applyInitialTheme();

    // Optional: Listen for system theme changes if you want to support 'system' preference reactively
    // This part is more complex if you want the UI to update without a reload when system theme changes
    // For now, 'system' preference is applied on load, and manual toggle overrides it.
  }, []);

  return (
    <html lang="en" suppressHydrationWarning>{/* suppressHydrationWarning for theme class changes */}
<head>
        <title>PR Visualizer</title> {/* Static title, or move to page.tsx for dynamic */}
        <meta name="description" content="Visualize your GitHub Pull Requests dynamically." />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;700&display=swap" rel="stylesheet" />
      </head><body className="font-body antialiased min-h-screen flex flex-col pb-24">
        {children}
        <BottomNavBar />
        <Toaster />
      </body>
    </html>
  );
}
